The goal of this notebook is to show how to use the deployed model:

In [1]:
from helpers import final_model_helper
import importlib

# Data preprocessing

Since there is more than one table, the first needs to be aggregated. I assume, that it is easier to preprocess the tables locally rather than uploading whole tables to cloud. If this was an actual database solution, the tables would be naturally integrated.

This can be done using just few commands with the provided aggregator.

In [2]:
importlib.reload(final_model_helper)
prep = final_model_helper.tables_to_input_converters("data/raw_csv", "models")

## Individual function confirmation
We first confirm that individual functions work properly

In [3]:
#prep.nb1_get_application_table().head()

In [4]:
#prep.nb5_bureau_balance_agg().head()

In [5]:
#prep.nb6_bureau_agg().head()

In [6]:
#prep.nb7_previous_applications().head()

In [7]:
if False:
    df = prep.prev_app
    columns_ending_xy = [col for col in df.columns if col.endswith(('x', 'y'))]
    print("Columns ending with 'x' or 'y':")
    print(columns_ending_xy)

In [8]:
pos = prep._get_prev_supp_table("POS_CASH_balance")
pos

Loading tables: ['POS_CASH_balance.csv']
loaded POS_CASH_balance with shape (10001358, 8)
dict_keys(['credit_status', 'bureau_overdue', 'time_variables', 'bureau', 'bureau_balance', 'pos_cash_balance', 'balance_limits', 'drawings_payments', 'contract_installments', 'credit_card_balance', 'previous_application', 'installments_payments'])
No missing columns.
No unexpected columns.
No missing columns.
No unexpected columns.

,SK_ID_CURR,prev_app_sum_MONTHS_BALANCE,prev_app_max_MONTHS_BALANCE,prev_app_median_MONTHS_BALANCE,prev_app_min_MONTHS_BALANCE,prev_app_std_MONTHS_BALANCE,prev_app_sum_CNT_INSTALMENT,prev_app_max_CNT_INSTALMENT,prev_app_median_CNT_INSTALMENT,prev_app_min_CNT_INSTALMENT,...,prev_app_max_SK_DPD_DEF,prev_app_median_SK_DPD_DEF,prev_app_min_SK_DPD_DEF,prev_app_std_SK_DPD_DEF,prev_app_onehot_count_NAME_CONTRACT_STATUS_A,prev_app_onehot_count_NAME_CONTRACT_STATUS_C,prev_app_onehot_count_NAME_CONTRACT_STATUS_D,prev_app_onehot_count_NAME_CONTRACT_STATUS_R,prev_app_onehot_count_NAME_CONTRACT_STATUS_S,prev_app_onehot_count_NAME_CONTRACT_STATUS_X
0,100001,-653,-53,-57.0,-96,20.863312,36.0,4.0,4.0,4.0,...,7,0.0,0,2.333333,7,0,0,0,0,0
1,100002,-190,-1,-10.0,-19,5.627314,456.0,24.0,24.0,24.0,...,0,0.0,0,0.000000,19,0,0,0,0,0
2,100003,-1226,-18,-26.5,-77,24.640162,283.0,12.0,12.0,6.0,...,0,0.0,0,0.000000,26,0,0,0,0,0
3,100004,-102,-24,-25.5,-27,1.290994,15.0,4.0,4.0,3.0,...,0,0.0,0,0.000000,3,0,0,0,0,0
4,100005,-220,-15,-20.0,-25,3.316625,117.0,12.0,12.0,9.0,...,0,0.0,0,0.000000,9,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337247,456251,-45,-1,-5.0,-9,2.738613,63.0,8.0,8.0,7.0,...,0,0.0,0,0.000000,7,0,0,0,1,0
337248,456252,-553,-76,-79.0,-82,2.160247,42.0,6.0,6.0,6.0,...,0,0.0,0,0.000000,6,0,0,0,0,0
337249,456253,-1347,-57,-90.0,-96,16.723970,114.0,12.0,6.0,4.0,...,5,0.0,0,1.212678,15,0,0,0,0,0
337250,456254,-111,-1,-5.5,-11,3.034451,298.0,16.0,14.0,14.0,...,0,0.0,0,0.000000,20,0,0,0,0,0
337251,456255,-1165,-2,-16.0,-33,7.426935,1618.0,36.0,24.0,3.0,...,5,0.0,0,0.593391,65,0,0,0,0,0

In [9]:
installments = prep._get_prev_supp_table("installments_payments")
installments

Loading tables: ['installments_payments.csv']
loaded installments_payments with shape (13605401, 8)
dict_keys(['credit_status', 'bureau_overdue', 'time_variables', 'bureau', 'bureau_balance', 'pos_cash_balance', 'balance_limits', 'drawings_payments', 'contract_installments', 'credit_card_balance', 'previous_application', 'installments_payments'])
No missing columns.
No unexpected columns.
No missing columns.
No unexpected columns.

,SK_ID_CURR,prev_app_sum_NUM_INSTALMENT_VERSION,prev_app_max_NUM_INSTALMENT_VERSION,prev_app_median_NUM_INSTALMENT_VERSION,prev_app_min_NUM_INSTALMENT_VERSION,prev_app_std_NUM_INSTALMENT_VERSION,prev_app_sum_NUM_INSTALMENT_NUMBER,prev_app_max_NUM_INSTALMENT_NUMBER,prev_app_median_NUM_INSTALMENT_NUMBER,prev_app_min_NUM_INSTALMENT_NUMBER,...,prev_app_sum_AMT_INSTALMENT,prev_app_max_AMT_INSTALMENT,prev_app_median_AMT_INSTALMENT,prev_app_min_AMT_INSTALMENT,prev_app_std_AMT_INSTALMENT,prev_app_sum_AMT_PAYMENT,prev_app_max_AMT_PAYMENT,prev_app_median_AMT_PAYMENT,prev_app_min_AMT_PAYMENT,prev_app_std_AMT_PAYMENT
0,100001,8.0,2.0,1.0,1.0,0.377964,19,4,3.0,1,...,41195.925,17397.900,3980.925,3951.000,5076.676624,41195.925,17397.900,3980.925,3951.000,5076.676624
1,100002,20.0,2.0,1.0,1.0,0.229416,190,19,10.0,1,...,219625.695,53093.745,9251.775,9251.775,10058.037722,219625.695,53093.745,9251.775,9251.775,10058.037722
2,100003,26.0,2.0,1.0,1.0,0.200000,127,12,5.0,1,...,1618864.650,560835.360,64275.615,6662.970,110542.592300,1618864.650,560835.360,64275.615,6662.970,110542.592300
3,100004,4.0,2.0,1.0,1.0,0.577350,6,3,2.0,1,...,21288.465,10573.965,5357.250,5357.250,3011.871810,21288.465,10573.965,5357.250,5357.250,3011.871810
4,100005,10.0,2.0,1.0,1.0,0.333333,45,9,5.0,1,...,56161.845,17656.245,4813.200,4813.200,4281.015000,56161.845,17656.245,4813.200,4813.200,4281.015000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339582,456251,8.0,2.0,1.0,1.0,0.377964,28,7,4.0,1,...,52450.470,12815.010,6605.910,6605.910,2346.819209,52450.470,12815.010,6605.910,6605.910,2346.819209
339583,456252,6.0,1.0,1.0,1.0,0.000000,21,6,3.5,1,...,60419.205,10074.465,10074.465,10046.880,11.261529,60419.205,10074.465,10074.465,10046.880,11.261529
339584,456253,14.0,1.0,1.0,1.0,0.000000,67,12,3.5,1,...,61595.910,5575.185,3973.095,2754.450,1145.446623,57622.815,5575.185,3973.095,27.270,1638.228743
339585,456254,19.0,1.0,1.0,1.0,0.000000,100,10,5.0,1,...,194556.825,19065.825,2296.440,2296.440,8602.512994,194556.825,19065.825,2296.440,2296.440,8602.512994
339586,456255,135.0,4.0,1.0,1.0,0.970215,655,24,7.0,1,...,3068388.810,615229.515,27489.690,11090.835,83407.926211,3525819.975,669251.655,27489.690,34.965,115619.974324

In [10]:
credit = prep._get_prev_supp_table("credit_card_balance")
credit

Loading tables: ['credit_card_balance.csv']
loaded credit_card_balance with shape (3840312, 23)
dict_keys(['credit_status', 'bureau_overdue', 'time_variables', 'bureau', 'bureau_balance', 'pos_cash_balance', 'balance_limits', 'drawings_payments', 'contract_installments', 'credit_card_balance', 'previous_application', 'installments_payments'])
No missing columns.
No unexpected columns.
No missing columns.
No unexpected columns.

,SK_ID_CURR,prev_app_sum_MONTHS_BALANCE,prev_app_max_MONTHS_BALANCE,prev_app_median_MONTHS_BALANCE,prev_app_min_MONTHS_BALANCE,prev_app_std_MONTHS_BALANCE,prev_app_sum_AMT_BALANCE,prev_app_max_AMT_BALANCE,prev_app_median_AMT_BALANCE,prev_app_min_AMT_BALANCE,...,prev_app_sum_SK_DPD_DEF,prev_app_max_SK_DPD_DEF,prev_app_median_SK_DPD_DEF,prev_app_min_SK_DPD_DEF,prev_app_std_SK_DPD_DEF,prev_app_onehot_count_NAME_CONTRACT_STATUS_A,prev_app_onehot_count_NAME_CONTRACT_STATUS_C,prev_app_onehot_count_NAME_CONTRACT_STATUS_D,prev_app_onehot_count_NAME_CONTRACT_STATUS_R,prev_app_onehot_count_NAME_CONTRACT_STATUS_S
0,100006,-21,-1,-3.5,-6,1.870829,0.000,0.000,0.0000,0.000,...,0,0,0.0,0,0.000000,6,0,0,0,0
1,100011,-2849,-2,-38.5,-75,21.505813,4031676.225,189000.000,0.0000,0.000,...,0,0,0.0,0,0.000000,74,0,0,0,0
2,100013,-4656,-1,-48.5,-96,27.856777,1743352.245,161420.220,0.0000,0.000,...,1,1,0.0,0,0.102062,96,0,0,0,0
3,100021,-170,-2,-10.0,-18,5.049752,0.000,0.000,0.0000,0.000,...,0,0,0.0,0,0.000000,7,10,0,0,0
4,100023,-60,-4,-7.5,-11,2.449490,0.000,0.000,0.0000,0.000,...,0,0,0.0,0,0.000000,8,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103553,456244,-861,-1,-21.0,-41,11.979149,5405223.960,453627.675,0.0000,0.000,...,0,0,0.0,0,0.000000,36,5,0,0,0
103554,456246,-44,-2,-5.5,-9,2.449490,105093.855,43490.115,753.4125,0.000,...,0,0,0.0,0,0.000000,8,0,0,0,0
103555,456247,-4655,-2,-49.0,-96,27.568098,2205557.640,190202.130,0.0000,0.000,...,2,1,0.0,0,0.144321,95,0,0,0,0
103556,456248,-299,-2,-13.0,-24,6.782330,0.000,0.000,0.0000,0.000,...,0,0,0.0,0,0.000000,23,0,0,0,0
103557,456250,-78,-1,-6.5,-12,3.605551,2083071.915,200208.915,173189.4525,153832.725,...,0,0,0.0,0,0.000000,12,0,0,0,0

### Single call
Or, for ease of use, the full data can be called with just a single line

In [ ]:
full_df = prep.get_full_input()
full_df.head()

Loading tables: ['application_train.csv']
loaded application_train with shape (307511, 122)
No missing columns.
Unexpected columns: ['SK_ID_CURR']
No missing columns.
Unexpected columns: ['SK_ID_CURR']
Loading tables: ['application_test.csv']
loaded application_test with shape (48744, 121)
No missing columns.
Unexpected columns: ['SK_ID_CURR']
No missing columns.
Unexpected columns: ['SK_ID_CURR']
Warning: Column 'TARGET' contains NaN values. These will become False.
No missing columns.
Unexpected columns: ['SK_ID_CURR']
Loading tables: ['bureau.csv']
loaded bureau with shape (1716428, 17)
dict_keys(['credit_status', 'bureau_overdue', 'time_variables', 'bureau', 'bureau_balance', 'pos_cash_balance', 'balance_limits', 'drawings_payments', 'contract_installments', 'credit_card_balance', 'previous_application', 'installments_payments'])
No missing columns.
No unexpected columns.
No missing columns.
No unexpected columns.
No missing columns.
No unexpected columns.
Filtering for currency: currency 1
Loading tables: ['bureau_balance.csv']
loaded bureau_balance with shape (27299925, 3)
dict_keys(['credit_status', 'bureau_overdue', 'time_variables', 'bureau', 'bureau_balance', 'pos_cash_balance', 'balance_limits', 'drawings_payments', 'contract_installments', 'credit_card_balance', 'previous_application', 'installments_payments'])
No missing columns.
No unexpected columns.
No missing columns.
No unexpected columns.
No missing columns.
No unexpected columns.
Relevant bureau balance shape: (610965, 5)
Available columns: ['SK_ID_CURR', 'SK_ID_BUREAU', 'CREDIT_ACTIVE', 'CREDIT_CURRENCY', 'DAYS_CREDIT', 'CREDIT_DAY_OVERDUE', 'DAYS_CREDIT_ENDDATE', 'DAYS_ENDDATE_FACT', 'AMT_CREDIT_MAX_OVERDUE', 'CNT_CREDIT_PROLONG', 'AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_DEBT', 'AMT_CREDIT_SUM_LIMIT', 'AMT_CREDIT_SUM_OVERDUE', 'CREDIT_TYPE', 'DAYS_CREDIT_UPDATE', 'AMT_ANNUITY', 'credit_usage', 'credit_duration', 'bur_bal_f_1', 'bur_bal_f_0', 'bur_bal_bad_payments']
CREDIT_ACTIVE unique values: ['Closed', 'Active', 'Other']
Categories (3, object): ['Active', 'Closed', 'Other']
Loading tables: ['previous_application.csv']
loaded previous_application with shape (1670214, 37)
dict_keys(['credit_status', 'bureau_overdue', 'time_variables', 'bureau', 'bureau_balance', 'pos_cash_balance', 'balance_limits', 'drawings_payments', 'contract_installments', 'credit_card_balance', 'previous_application', 'installments_payments'])
Warning: Column 'PRODUCT_COMBINATION' contains NaN values. These will become False.
No missing columns.
No unexpected columns.
No missing columns.
No unexpected columns.
No missing columns.
No unexpected columns.
Loading tables: ['POS_CASH_balance.csv']
loaded POS_CASH_balance with shape (10001358, 8)
dict_keys(['credit_status', 'bureau_overdue', 'time_variables', 'bureau', 'bureau_balance', 'pos_cash_balance', 'balance_limits', 'drawings_payments', 'contract_installments', 'credit_card_balance', 'previous_application', 'installments_payments'])
No missing columns.
No unexpected columns.
No missing columns.
No unexpected columns.
Loading tables: ['installments_payments.csv']
loaded installments_payments with shape (13605401, 8)
dict_keys(['credit_status', 'bureau_overdue', 'time_variables', 'bureau', 'bureau_balance', 'pos_cash_balance', 'balance_limits', 'drawings_payments', 'contract_installments', 'credit_card_balance', 'previous_application', 'installments_payments'])
No missing columns.
No unexpected columns.
No missing columns.
No unexpected columns.
Loading tables: ['credit_card_balance.csv']
loaded credit_card_balance with shape (3840312, 23)
dict_keys(['credit_status', 'bureau_overdue', 'time_variables', 'bureau', 'bureau_balance', 'pos_cash_balance', 'balance_limits', 'drawings_payments', 'contract_installments', 'credit_card_balance', 'previous_application', 'installments_payments'])
No missing columns.
No unexpected columns.
No missing columns.
No unexpected columns.

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,prev_app_sum_SK_DPD_DEF_y,prev_app_max_SK_DPD_DEF_y,prev_app_median_SK_DPD_DEF_y,prev_app_min_SK_DPD_DEF_y,prev_app_std_SK_DPD_DEF_y,prev_app_onehot_count_NAME_CONTRACT_STATUS_A_y,prev_app_onehot_count_NAME_CONTRACT_STATUS_C_y,prev_app_onehot_count_NAME_CONTRACT_STATUS_D_y,prev_app_onehot_count_NAME_CONTRACT_STATUS_R_y,prev_app_onehot_count_NAME_CONTRACT_STATUS_S_y
0,100002,True,Cash loans,M,False,True,0,202500.0,406597.5,24700.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,100003,False,Cash loans,F,False,False,0,270000.0,1293502.5,35698.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,100004,False,Revolving loans,M,True,True,0,67500.0,135000.0,6750.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,100006,False,Cash loans,F,False,True,0,135000.0,312682.5,29686.5,...,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0
4,100007,False,Cash loans,M,False,True,0,121500.0,513000.0,21865.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
full_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Columns: 749 entries, SK_ID_CURR to prev_app_onehot_count_NAME_CONTRACT_STATUS_S_y
dtypes: bool(35), category(14), float64(693), int64(6), object(1)
memory usage: 33.6+ KB

In [14]:
import joblib
notebook_df = joblib.load("data/processed/all_tables.jbl")
notebook_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356255 entries, 0 to 356254
Columns: 467 entries, SK_ID_CURR to prev_app_onehot_count_NAME_CONTRACT_STATUS_X
dtypes: bool(34), category(14), float64(412), int64(6), object(1)
memory usage: 1.1+ GB

In [ ]:
extra_cols = set(full_df.columns) - set(notebook_df.columns)
print(len(extra_cols))
extra_cols

327 extra columns in full_df compared to notebook_df:

{'max_AMT_ANNUITY',
 'max_AMT_APPLICATION',
 'max_AMT_CREDIT',
 'max_AMT_DOWN_PAYMENT',
 'max_AMT_GOODS_PRICE',
 'max_CNT_PAYMENT',
 'max_DAYS_DECISION',
 'max_DAYS_FIRST_DRAWING',
 'max_DAYS_FIRST_DUE',
 'max_DAYS_LAST_DUE',
 'max_DAYS_LAST_DUE_1ST_VERSION',
 'max_DAYS_TERMINATION',
 'max_HOUR_APPR_PROCESS_START',
 'max_NFLAG_INSURED_ON_APPROVAL',
 'max_RATE_DOWN_PAYMENT',
 'max_RATE_INTEREST_PRIMARY',
 'max_RATE_INTEREST_PRIVILEGED',
 'max_SELLERPLACE_AREA',
 'median_AMT_ANNUITY',
 'median_AMT_APPLICATION',
 'median_AMT_CREDIT',
 'median_AMT_DOWN_PAYMENT',
 'median_AMT_GOODS_PRICE',
 'median_CNT_PAYMENT',
 'median_DAYS_DECISION',
 'median_DAYS_FIRST_DRAWING',
 'median_DAYS_FIRST_DUE',
 'median_DAYS_LAST_DUE',
 'median_DAYS_LAST_DUE_1ST_VERSION',
 'median_DAYS_TERMINATION',
 'median_HOUR_APPR_PROCESS_START',
 'median_NFLAG_INSURED_ON_APPROVAL',
 'median_RATE_DOWN_PAYMENT',
 'median_RATE_INTEREST_PRIMARY',
 'median_RATE_INTEREST_PRIVILEGED',
 'median_SELLERPLACE_AREA',
 'median_bur_bal_bad_payments_Active',
 'median_bur_bal_bad_payments_Closed',
 'median_bur_bal_bad_payments_Other',
 'min_AMT_ANNUITY',
 'min_AMT_APPLICATION',
 'min_AMT_CREDIT',
 'min_AMT_DOWN_PAYMENT',
 'min_AMT_GOODS_PRICE',
 'min_CNT_PAYMENT',
 'min_DAYS_DECISION',
 'min_DAYS_FIRST_DRAWING',
 'min_DAYS_FIRST_DUE',
 'min_DAYS_LAST_DUE',
 'min_DAYS_LAST_DUE_1ST_VERSION',
 'min_DAYS_TERMINATION',
 'min_HOUR_APPR_PROCESS_START',
 'min_NFLAG_INSURED_ON_APPROVAL',
 'min_RATE_DOWN_PAYMENT',
 'min_RATE_INTEREST_PRIMARY',
 'min_RATE_INTEREST_PRIVILEGED',
 'min_SELLERPLACE_AREA',
 'onehot_count_CHANNEL_TYPE_A',
 'onehot_count_CHANNEL_TYPE_C',
 'onehot_count_CHANNEL_TYPE_R',
 'onehot_count_CHANNEL_TYPE_S',
 'onehot_count_CODE_REJECT_REASON_C',
 'onehot_count_CODE_REJECT_REASON_H',
 'onehot_count_CODE_REJECT_REASON_L',
 'onehot_count_CODE_REJECT_REASON_S',
 'onehot_count_CODE_REJECT_REASON_V',
 'onehot_count_CODE_REJECT_REASON_X',
 'onehot_count_CREDIT_CURRENCY_c_Active',
 'onehot_count_CREDIT_CURRENCY_c_Closed',
 'onehot_count_CREDIT_CURRENCY_c_Other',
 'onehot_count_NAME_CASH_LOAN_PURPOSE_B',
 'onehot_count_NAME_CASH_LOAN_PURPOSE_C',
 'onehot_count_NAME_CASH_LOAN_PURPOSE_E',
 'onehot_count_NAME_CASH_LOAN_PURPOSE_F',
 'onehot_count_NAME_CASH_LOAN_PURPOSE_G',
 'onehot_count_NAME_CASH_LOAN_PURPOSE_H',
 'onehot_count_NAME_CASH_LOAN_PURPOSE_J',
 'onehot_count_NAME_CASH_LOAN_PURPOSE_M',
 'onehot_count_NAME_CASH_LOAN_PURPOSE_O',
 'onehot_count_NAME_CASH_LOAN_PURPOSE_P',
 'onehot_count_NAME_CASH_LOAN_PURPOSE_R',
 'onehot_count_NAME_CASH_LOAN_PURPOSE_U',
 'onehot_count_NAME_CASH_LOAN_PURPOSE_W',
 'onehot_count_NAME_CASH_LOAN_PURPOSE_X',
 'onehot_count_NAME_CLIENT_TYPE_N',
 'onehot_count_NAME_CLIENT_TYPE_R',
 'onehot_count_NAME_CLIENT_TYPE_X',
 'onehot_count_NAME_CONTRACT_STATUS_A',
 'onehot_count_NAME_CONTRACT_STATUS_C',
 'onehot_count_NAME_CONTRACT_STATUS_R',
 'onehot_count_NAME_CONTRACT_STATUS_U',
 'onehot_count_NAME_CONTRACT_TYPE_C',
 'onehot_count_NAME_CONTRACT_TYPE_R',
 'onehot_count_NAME_CONTRACT_TYPE_X',
 'onehot_count_NAME_GOODS_CATEGORY_A',
 'onehot_count_NAME_GOODS_CATEGORY_C',
 'onehot_count_NAME_GOODS_CATEGORY_D',
 'onehot_count_NAME_GOODS_CATEGORY_E',
 'onehot_count_NAME_GOODS_CATEGORY_F',
 'onehot_count_NAME_GOODS_CATEGORY_G',
 'onehot_count_NAME_GOODS_CATEGORY_H',
 'onehot_count_NAME_GOODS_CATEGORY_I',
 'onehot_count_NAME_GOODS_CATEGORY_J',
 'onehot_count_NAME_GOODS_CATEGORY_M',
 'onehot_count_NAME_GOODS_CATEGORY_O',
 'onehot_count_NAME_GOODS_CATEGORY_P',
 'onehot_count_NAME_GOODS_CATEGORY_S',
 'onehot_count_NAME_GOODS_CATEGORY_T',
 'onehot_count_NAME_GOODS_CATEGORY_V',
 'onehot_count_NAME_GOODS_CATEGORY_W',
 'onehot_count_NAME_GOODS_CATEGORY_X',
 'onehot_count_NAME_PAYMENT_TYPE_C',
 'onehot_count_NAME_PAYMENT_TYPE_N',
 'onehot_count_NAME_PAYMENT_TYPE_X',
 'onehot_count_NAME_PORTFOLIO_C',
 'onehot_count_NAME_PORTFOLIO_P',
 'onehot_count_NAME_PORTFOLIO_X',
 'onehot_count_NAME_PRODUCT_TYPE_X',
 'onehot_count_NAME_PRODUCT_TYPE_w',
 'onehot_count_NAME_PRODUCT_TYPE_x',
 'onehot_count_NAME_SELLER_INDUSTRY_A',
 'onehot_count_NAME_SELLER_INDUSTRY_C',
 'onehot_count_NAME_SELLER_INDUSTRY_F',
 'onehot_count_NAME_SELLER_INDUSTRY_I',
 'onehot_count_NAME_SELLER_INDUSTRY_J',
 'onehot_count_NAME_SELLER_INDUSTRY_M',
 'onehot_count_NAME_SELLER_INDUSTRY_T',
 'onehot_count_NAME_SELLER_INDUSTRY_X',
 'onehot_count_NAME_TYPE_SUITE_C',
 'onehot_count_NAME_TYPE_SUITE_F',
 'onehot_count_NAME_TYPE_SUITE_G',
 'onehot_count_NAME_TYPE_SUITE_O',
 'onehot_count_NAME_TYPE_SUITE_S',
 'onehot_count_NAME_TYPE_SUITE_U',
 'onehot_count_NAME_YIELD_GROUP_X',
 'onehot_count_NAME_YIELD_GROUP_h',
 'onehot_count_NAME_YIELD_GROUP_l',
 'onehot_count_NAME_YIELD_GROUP_m',
 'onehot_count_WEEKDAY_APPR_PROCESS_START_F',
 'onehot_count_WEEKDAY_APPR_PROCESS_START_M',
 'onehot_count_WEEKDAY_APPR_PROCESS_START_S',
 'onehot_count_WEEKDAY_APPR_PROCESS_START_T',
 'onehot_count_WEEKDAY_APPR_PROCESS_START_W',
 'onehot_count_bur_bal_f_1_0_Active',
 'onehot_count_bur_bal_f_1_0_Closed',
 'onehot_count_bur_bal_f_1_0_Other',
 'onehot_count_bur_bal_f_1_1_Active',
 'onehot_count_bur_bal_f_1_1_Closed',
 'onehot_count_bur_bal_f_1_1_Other',
 'onehot_count_bur_bal_f_1_2_Active',
 'onehot_count_bur_bal_f_1_2_Closed',
 'onehot_count_bur_bal_f_1_2_Other',
 'onehot_count_bur_bal_f_1_3_Active',
 'onehot_count_bur_bal_f_1_3_Closed',
 'onehot_count_bur_bal_f_1_3_Other',
 'onehot_count_bur_bal_f_1_4_Active',
 'onehot_count_bur_bal_f_1_4_Closed',
 'onehot_count_bur_bal_f_1_4_Other',
 'onehot_count_bur_bal_f_1_5_Active',
 'onehot_count_bur_bal_f_1_5_Closed',
 'onehot_count_bur_bal_f_1_5_Other',
 'onehot_count_bur_bal_f_1_C_Active',
 'onehot_count_bur_bal_f_1_C_Closed',
 'onehot_count_bur_bal_f_1_C_Other',
 'onehot_count_bur_bal_f_1_X_Active',
 'onehot_count_bur_bal_f_1_X_Closed',
 'onehot_count_bur_bal_f_1_X_Other',
 'prev_app_max_AMT_BALANCE',
 'prev_app_max_AMT_CREDIT_LIMIT_ACTUAL',
 'prev_app_max_AMT_DRAWINGS_ATM_CURRENT',
 'prev_app_max_AMT_DRAWINGS_CURRENT',
 'prev_app_max_AMT_DRAWINGS_OTHER_CURRENT',
 'prev_app_max_AMT_DRAWINGS_POS_CURRENT',
 'prev_app_max_AMT_INSTALMENT',
 'prev_app_max_AMT_INST_MIN_REGULARITY',
 'prev_app_max_AMT_PAYMENT',
 'prev_app_max_AMT_PAYMENT_CURRENT',
 'prev_app_max_AMT_PAYMENT_TOTAL_CURRENT',
 'prev_app_max_AMT_RECEIVABLE_PRINCIPAL',
 'prev_app_max_AMT_RECIVABLE',
 'prev_app_max_AMT_TOTAL_RECEIVABLE',
 'prev_app_max_CNT_DRAWINGS_ATM_CURRENT',
 'prev_app_max_CNT_DRAWINGS_CURRENT',
 'prev_app_max_CNT_DRAWINGS_OTHER_CURRENT',
 'prev_app_max_CNT_DRAWINGS_POS_CURRENT',
 'prev_app_max_CNT_INSTALMENT_MATURE_CUM',
 'prev_app_max_DAYS_ENTRY_PAYMENT',
 'prev_app_max_DAYS_INSTALMENT',
 'prev_app_max_NUM_INSTALMENT_NUMBER',
 'prev_app_max_NUM_INSTALMENT_VERSION',
 'prev_app_median_AMT_BALANCE',
 'prev_app_median_AMT_CREDIT_LIMIT_ACTUAL',
 'prev_app_median_AMT_DRAWINGS_ATM_CURRENT',
 'prev_app_median_AMT_DRAWINGS_CURRENT',
 'prev_app_median_AMT_DRAWINGS_OTHER_CURRENT',
 'prev_app_median_AMT_DRAWINGS_POS_CURRENT',
 'prev_app_median_AMT_INSTALMENT',
 'prev_app_median_AMT_INST_MIN_REGULARITY',
 'prev_app_median_AMT_PAYMENT',
 'prev_app_median_AMT_PAYMENT_CURRENT',
 'prev_app_median_AMT_PAYMENT_TOTAL_CURRENT',
 'prev_app_median_AMT_RECEIVABLE_PRINCIPAL',
 'prev_app_median_AMT_RECIVABLE',
 'prev_app_median_AMT_TOTAL_RECEIVABLE',
 'prev_app_median_CNT_DRAWINGS_ATM_CURRENT',
 'prev_app_median_CNT_DRAWINGS_CURRENT',
 'prev_app_median_CNT_DRAWINGS_OTHER_CURRENT',
 'prev_app_median_CNT_DRAWINGS_POS_CURRENT',
 'prev_app_median_CNT_INSTALMENT_MATURE_CUM',
 'prev_app_median_DAYS_ENTRY_PAYMENT',
 'prev_app_median_DAYS_INSTALMENT',
 'prev_app_median_NUM_INSTALMENT_NUMBER',
 'prev_app_median_NUM_INSTALMENT_VERSION',
 'prev_app_min_AMT_BALANCE',
 'prev_app_min_AMT_CREDIT_LIMIT_ACTUAL',
 'prev_app_min_AMT_DRAWINGS_ATM_CURRENT',
 'prev_app_min_AMT_DRAWINGS_CURRENT',
 'prev_app_min_AMT_DRAWINGS_OTHER_CURRENT',
 'prev_app_min_AMT_DRAWINGS_POS_CURRENT',
 'prev_app_min_AMT_INSTALMENT',
 'prev_app_min_AMT_INST_MIN_REGULARITY',
 'prev_app_min_AMT_PAYMENT',
 'prev_app_min_AMT_PAYMENT_CURRENT',
 'prev_app_min_AMT_PAYMENT_TOTAL_CURRENT',
 'prev_app_min_AMT_RECEIVABLE_PRINCIPAL',
 'prev_app_min_AMT_RECIVABLE',
 'prev_app_min_AMT_TOTAL_RECEIVABLE',
 'prev_app_min_CNT_DRAWINGS_ATM_CURRENT',
 'prev_app_min_CNT_DRAWINGS_CURRENT',
 'prev_app_min_CNT_DRAWINGS_OTHER_CURRENT',
 'prev_app_min_CNT_DRAWINGS_POS_CURRENT',
 'prev_app_min_CNT_INSTALMENT_MATURE_CUM',
 'prev_app_min_DAYS_ENTRY_PAYMENT',
 'prev_app_min_DAYS_INSTALMENT',
 'prev_app_min_NUM_INSTALMENT_NUMBER',
 'prev_app_min_NUM_INSTALMENT_VERSION',
 'prev_app_std_AMT_BALANCE',
 'prev_app_std_AMT_CREDIT_LIMIT_ACTUAL',
 'prev_app_std_AMT_DRAWINGS_ATM_CURRENT',
 'prev_app_std_AMT_DRAWINGS_CURRENT',
 'prev_app_std_AMT_DRAWINGS_OTHER_CURRENT',
 'prev_app_std_AMT_DRAWINGS_POS_CURRENT',
 'prev_app_std_AMT_INSTALMENT',
 'prev_app_std_AMT_INST_MIN_REGULARITY',
 'prev_app_std_AMT_PAYMENT',
 'prev_app_std_AMT_PAYMENT_CURRENT',
 'prev_app_std_AMT_PAYMENT_TOTAL_CURRENT',
 'prev_app_std_AMT_RECEIVABLE_PRINCIPAL',
 'prev_app_std_AMT_RECIVABLE',
 'prev_app_std_AMT_TOTAL_RECEIVABLE',
 'prev_app_std_CNT_DRAWINGS_ATM_CURRENT',
 'prev_app_std_CNT_DRAWINGS_CURRENT',
 'prev_app_std_CNT_DRAWINGS_OTHER_CURRENT',
 'prev_app_std_CNT_DRAWINGS_POS_CURRENT',
 'prev_app_std_CNT_INSTALMENT_MATURE_CUM',
 'prev_app_std_DAYS_ENTRY_PAYMENT',
 'prev_app_std_DAYS_INSTALMENT',
 'prev_app_std_NUM_INSTALMENT_NUMBER',
 'prev_app_std_NUM_INSTALMENT_VERSION',
 'prev_app_sum_AMT_BALANCE',
 'prev_app_sum_AMT_CREDIT_LIMIT_ACTUAL',
 'prev_app_sum_AMT_DRAWINGS_ATM_CURRENT',
 'prev_app_sum_AMT_DRAWINGS_CURRENT',
 'prev_app_sum_AMT_DRAWINGS_OTHER_CURRENT',
 'prev_app_sum_AMT_DRAWINGS_POS_CURRENT',
 'prev_app_sum_AMT_INSTALMENT',
 'prev_app_sum_AMT_INST_MIN_REGULARITY',
 'prev_app_sum_AMT_PAYMENT',
 'prev_app_sum_AMT_PAYMENT_CURRENT',
 'prev_app_sum_AMT_PAYMENT_TOTAL_CURRENT',
 'prev_app_sum_AMT_RECEIVABLE_PRINCIPAL',
 'prev_app_sum_AMT_RECIVABLE',
 'prev_app_sum_AMT_TOTAL_RECEIVABLE',
 'prev_app_sum_CNT_DRAWINGS_ATM_CURRENT',
 'prev_app_sum_CNT_DRAWINGS_CURRENT',
 'prev_app_sum_CNT_DRAWINGS_OTHER_CURRENT',
 'prev_app_sum_CNT_DRAWINGS_POS_CURRENT',
 'prev_app_sum_CNT_INSTALMENT_MATURE_CUM',
 'prev_app_sum_DAYS_ENTRY_PAYMENT',
 'prev_app_sum_DAYS_INSTALMENT',
 'prev_app_sum_NUM_INSTALMENT_NUMBER',
 'prev_app_sum_NUM_INSTALMENT_VERSION',
 'std_AMT_ANNUITY',
 'std_AMT_APPLICATION',
 'std_AMT_CREDIT',
 'std_AMT_DOWN_PAYMENT',
 'std_AMT_GOODS_PRICE',
 'std_CNT_PAYMENT',
 'std_DAYS_DECISION',
 'std_DAYS_FIRST_DRAWING',
 'std_DAYS_FIRST_DUE',
 'std_DAYS_LAST_DUE',
 'std_DAYS_LAST_DUE_1ST_VERSION',
 'std_DAYS_TERMINATION',
 'std_HOUR_APPR_PROCESS_START',
 'std_NFLAG_INSURED_ON_APPROVAL',
 'std_RATE_DOWN_PAYMENT',
 'std_RATE_INTEREST_PRIMARY',
 'std_RATE_INTEREST_PRIVILEGED',
 'std_SELLERPLACE_AREA',
 'std_bur_bal_bad_payments_Active',
 'std_bur_bal_bad_payments_Closed',
 'std_bur_bal_bad_payments_Other',
 'std_credit_duration_Active',
 'std_credit_duration_Closed',
 'std_credit_duration_Other',
 'std_credit_usage_Active',
 'std_credit_usage_Closed',
 'std_credit_usage_Other',
 'sum_AMT_ANNUITY',
 'sum_AMT_APPLICATION',
 'sum_AMT_CREDIT',
 'sum_AMT_DOWN_PAYMENT',
 'sum_AMT_GOODS_PRICE',
 'sum_CNT_PAYMENT',
 'sum_DAYS_DECISION',
 'sum_DAYS_FIRST_DRAWING',
 'sum_DAYS_FIRST_DUE',
 'sum_DAYS_LAST_DUE',
 'sum_DAYS_LAST_DUE_1ST_VERSION',
 'sum_DAYS_TERMINATION',
 'sum_HOUR_APPR_PROCESS_START',
 'sum_NFLAG_INSURED_ON_APPROVAL',
 'sum_RATE_DOWN_PAYMENT',
 'sum_RATE_INTEREST_PRIMARY',
 'sum_RATE_INTEREST_PRIVILEGED',
 'sum_SELLERPLACE_AREA'}